import {EpsThemeRegistry,EPS_THEME_IDS} from './themes/eps-themes.js?v=0.13.0';
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const APP_VERSION='0.13.0';
const DEV_PRO_CODE='1234';
const epsThemeRegistry=new EpsThemeRegistry();
const THEME_CYCLE=['mydiag','dark','ivory',...EPS_THEME_IDS];
const hasSavedVehicle=localStorage.getItem('ecuVehicle')!==null;
const state={data:null,tiers:null,logos:null,demo:null,plan:localStorage.getItem('ecuDevProUnlocked')==='true'?'pro':'free',theme:localStorage.getItem('ecuTheme')||'mydiag',vehicleIndex:Number(localStorage.getItem('ecuVehicle')||0),demoMode:localStorage.getItem('ecuDemoMode')!==null?localStorage.getItem('ecuDemoMode')==='true':!hasSavedVehicle,customLogo:localStorage.getItem('ecuCustomLogo')||'',mockTimer:null,demoTick:0,live:{rpm:0,speedKph:0,coolantC:null,voltage:null,engineLoad:null},dtcs:[],errors:JSON.parse(localStorage.getItem('ecuErrors')||'[]'),token:null,tokenExp:0,offers:[],lastReport:null,trip:{watchId:null,startedAt:0,points:[],replayTimer:null,replayFrame:null,replayIndex:0,replaySpeed:1,paused:false,currentTrip:null,projection:null,currentHeading:0},map:null,mapLoading:null,routeLine:null,replayMarker:null,stopMarkers:[],activeApi:null};
const installationId=localStorage.getItem('ecuInstallationId')||crypto.randomUUID();localStorage.setItem('ecuInstallationId',installationId);
document.documentElement.dataset.theme=state.theme;

class AppFault extends Error{constructor(code,title,detail,context={}){super(detail||title);this.name='AppFault';this.code=code;this.title=title;this.detail=detail||title;this.context=context}}
function sanitize(x){const clone=JSON.parse(JSON.stringify(x||{}));for(const k of Object.keys(clone))if(/token|password|secret|vin/i.test(k))clone[k]='[REDACTED]';return clone}
function persistErrors(){localStorage.setItem('ecuErrors',JSON.stringify(state.errors.slice(-100)))}
function reportError(error,context={},show=true){if(error?.name==='AbortError')return null;const fault=error instanceof AppFault?error:new AppFault(error?.code||'UNKNOWN_ERROR','خطای ناشناخته',`${error?.name||'Error'}: ${error?.message||String(error)}`,context);const item={id:crypto.randomUUID(),at:new Date().toISOString(),code:fault.code,title:fault.title,detail:fault.detail,context:sanitize({...context,...fault.context}),sent:false,platform:'web',appVersion:APP_VERSION};state.errors.push(item);persistErrors();renderErrors();if(show)showError(item);console.error('[ECU Pulse]',item);return item}
window.addEventListener('error',e=>reportError(e.error||new Error(e.message),{file:e.filename,line:e.lineno},true));window.addEventListener('unhandledrejection',e=>reportError(e.reason||new Error('Unhandled rejection'),{source:'promise'},true));
function openErrorDialog(){
  const dialog=$('#errorDialog');
  if(!dialog)return;
  dialog.hidden=false;
  dialog.setAttribute('aria-hidden','false');
  requestAnimationFrame(()=>$('#dismissError')?.focus());
}
function closeErrorDialog(){
  const dialog=$('#errorDialog');
  if(!dialog)return;
  dialog.hidden=true;
  dialog.setAttribute('aria-hidden','true');
}
function showError(item){
  $('#errorCode').textContent=item.code||'UNKNOWN_ERROR';
  $('#errorTitle').textContent=item.title||'خطای ناشناخته';
  $('#errorDetail').textContent=item.detail||'جزئیات بیشتری از خطا دریافت نشد.';
  $('#sendError').onclick=()=>sendError(item.id);
  openErrorDialog();
}
$('#dismissError').onclick=closeErrorDialog;
$('#errorDialog').addEventListener('click',event=>{
  if(event.target===event.currentTarget)closeErrorDialog();
});
window.addEventListener('keydown',event=>{
  if(event.key==='Escape'&&!$('#errorDialog').hidden)closeErrorDialog();
});
function toast(text){const n=$('#toast');n.textContent=text;n.classList.add('show');setTimeout(()=>n.classList.remove('show'),2000)}
function fa(v){return String(v).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d])}
async function fetchTimeout(url,opt={},timeout=10000,retries=1){let last;for(let i=0;i<=retries;i++){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const r=await fetch(url,{...opt,signal:controller.signal});clearTimeout(timer);if(!r.ok){let j={};try{j=await r.json()}catch{}throw new AppFault(j.error?.code||`HTTP_${r.status}`,j.error?.title||'خطای ارتباط با سرور',j.error?.detail||`${r.status} ${r.statusText}`,{url})}return r}catch(e){clearTimeout(timer);last=e;if(i<retries)await new Promise(r=>setTimeout(r,500*2**i))}}throw last}
async function loadJson(url){return fetchTimeout(url,{},8000,1).then(r=>r.json())}
function apiBases(){const local=localStorage.getItem('ecuLocalApi')||'http://127.0.0.1:4030',remote=localStorage.getItem('ecuRemoteApi')||'https://diageman.ir';return [...new Set([$('#apiBase')?.value,local,remote].filter(Boolean).map(x=>x.replace(/\/$/,'')))]}
async function ensureToken(force=false){if(!force&&state.token&&Date.now()<state.tokenExp)return state.token;let last;for(const base of apiBases()){try{const r=await fetchTimeout(`${base}/api/v1/auth/exchange`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({clientId:'ecu-pulse-web',installationId,store:'web',devMode:true,requestedPlan:state.plan})},6000,0);const x=await r.json();state.token=x.accessToken;state.tokenExp=Date.now()+(x.expiresIn-30)*1000;state.activeApi=base;return state.token}catch(e){last=e}}throw last||new AppFault('API_OFFLINE','سرور در دسترس نیست','هیچ‌کدام از آدرس‌های API پاسخ ندادند.')}
async function api(path,opt={}){const token=await ensureToken();const base=state.activeApi||apiBases()[0];return fetchTimeout(`${base}${path}`,{...opt,headers:{'content-type':'application/json',authorization:`Bearer ${token}`,...opt.headers}},10000,1)}

function go(page){$$('.page').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$$('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const meta={mydiag:['SMART VEHICLE','خانه خودرو'],drivingstyle:['DRIVING STYLE','سبک رانندگی'],parking:['PARKING MEMORY','محل پارک'],dashcam:['DASHCAM','دوربین خودرو'],dashboard:['LIVE VEHICLE','داشبورد خودرو'],vehicles:['VEHICLE PROFILE','انتخاب خودرو'],trips:['GPS TRIP LOGGER','سفرها'],analysis:['DIAGEMAN API','تحلیل ماشین من'],procenter:['ADVANCED CENTER','مرکز نسخه پیشرفته'],store:['UPGRADE','خرید و فعال‌سازی'],errors:['FAULT CENTER','خطا و پشتیبانی'],scanner:['ELM327 CONSOLE','اسکنر و کنسول ECU'],settings:['SETTINGS','تنظیمات']};const selected=meta[page]||meta.dashboard;$('#eyebrow').textContent=selected[0];$('#title').textContent=selected[1];$('aside').classList.remove('open');if(page==='trips')setTimeout(async()=>{await initMap();previewSelectedTrip();state.map?.invalidateSize?.(true)},80);if(page==='store')loadOffers()}
$$('button[data-page], [role="button"][data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));
$$('.mydiag-menu-card[data-target]').forEach(b=>b.onclick=()=>{go(b.dataset.target);if(b.dataset.anchor)setTimeout(()=>document.getElementById(b.dataset.anchor)?.scrollIntoView({behavior:'smooth',block:'center'}),120)});
$$('.mydiag-menu-card[data-special]').forEach(b=>b.onclick=()=>go(b.dataset.special.replace('-','')));$('#menuBtn').onclick=()=>$('aside').classList.toggle('open');
function applyTheme(v){
  state.theme=THEME_CYCLE.includes(v)?v:'mydiag';
  document.documentElement.dataset.theme=state.theme;
  localStorage.setItem('ecuTheme',state.theme);
  if($('#themeSelect'))$('#themeSelect').value=state.theme;
  epsThemeRegistry.apply(state.theme,$('#epsThemePanel'),state.live);
}
$('#themeBtn').onclick=()=>{
  const i=THEME_CYCLE.indexOf(state.theme);
  applyTheme(THEME_CYCLE[(i+1)%THEME_CYCLE.length]);
};

const brandRules=[
['parskhodro',/پارس.?خودرو/],['ikcodiesel',/ایران.?خودرو دیزل/],['bahmandiesel',/بهمن دیزل/],
['fownix',/فونیکس|FOWNIX|تیگو 7|تیگو 8|FX/],['mvm',/MVM|X22|X33|X55|آریزو/],['modirankhodro',/مدیران خودرو/],
['kmc',/KMC/],['jac',/جک|JAC/],['kermanmotor',/کرمان موتور/],['lamari',/آرین پارس|لاماری/],
['farda',/فردا موتور|FMC|SUBA/],['diar',/دیار خودرو/],['mammut',/ماموت خودرو/],['zamyad',/زامیاد|پادرا|کارون/],
['bahman',/بهمن موتور|فیدلیتی|دیگنیتی|ریسپکت|کاپرا/],['ikco',/ایران.?خودرو|رانا|سمند|سورن|دنا|تارا|ری.?را/],
['saipa',/سایپا|پراید|تیبا|ساینا|کوییک|اطلس|شاهین/],['lexus',/لکسوس|Lexus|RX|NX/],['audi',/آئودی|Audi|A3|A4|Q5/],
['skoda',/اشکودا|اوکتاویا/],['volkswagen',/فولکس|Volkswagen|گلف|پاسات|تیگوان/],['citroen',/سیتروئن|C3|C5/],
['peugeot',/پژو|Peugeot|۲۰۶|۲۰۷|۳۰۱|۲۰۰۸/],['renault',/رنو|Renault|تندر|ساندرو|لوگان|داستر|کپچر|مگان/],
['mercedesbenz',/مرسدس|بنز|Actros|Axor|Atego/],['bmw',/BMW|ب.?ام.?و/],['mini',/MINI/],['toyota',/تویوتا|Toyota|کرولا|کمری|پریوس|RAV4|لندکروزر|هایلوکس/],
['hyundaicommercial',/هیوندای تجاری|HD65|HD78|Xcient/],['hyundai',/هیوندای|Hyundai|اکسنت|النترا|سوناتا|آزرا|توسان|سانتافه/],
['kia',/کیا|Kia|ریو|سراتو|اپتیما|اسپورتیج|سورنتو/],['nissan',/نیسان|Nissan|ماکسیما|مورانو|قشقایی|جوک|تیانا/],
['mitsubishi',/میتسوبیشی|Mitsubishi|لنسر|اوتلندر|پاجرو/],['mazda',/مزدا|Mazda/],['suzuki',/سوزوکی|Suzuki|ویتارا/],
['honda',/هوندا|Honda|سیویک|آکورد/],['opel',/اوپل|Opel|آسترا|کورسا/],['ford',/فورد|Ford/],['chevrolet',/شورولت|Chevrolet/],
['subaru',/سابارو|Subaru/],['mg',/(^|\s)MG/],['geely',/جیلی|Geely/],['changan',/چانگان|Changan/],['byd',/BYD/],
['haval',/هاوال|Haval/],['greatwall',/گریت.?وال|وینگل|Great Wall/],['dongfeng',/دانگ.?فنگ|Dongfeng/],['faw',/فاو|FAW|بسترن|Bestune/],
['brilliance',/برلیانس|Brilliance/],['baic',/BAIC/],['scania',/اسکانیا|Scania/],['volvotrucks',/ولوو تراکس|FH|FMX/],
['volvo',/ولوو|Volvo/],['isuzu',/ایسوزو|Isuzu/],['iveco',/ایویکو|Iveco/],['daf',/داف|DAF/],['man',/(^|\s)مان(\s|$)|MAN|TGX|TGS/],
['foton',/فوتون|آومان|Foton|Auman/],['shacman',/شاکمن|Shacman/],['kamaz',/کاماز|Kamaz/],['dayun',/دایون|Dayun/],['generic',/.*/]
];
function brandKey(v){const text=`${v?.make||''} ${v?.model||''}`;return brandRules.find(x=>x[1].test(text))?.[0]||'generic'}
function logoMeta(v){const key=brandKey(v);return state.logos?.brands?.find(x=>x.key===key)}
function logoPath(v){const key=brandKey(v),meta=logoMeta(v);return meta?.png||meta?.file||meta?.fallback||`assets/logos/fallback/${key}.svg`}
function logoFallback(v){const key=brandKey(v),meta=logoMeta(v);return meta?.fallback||meta?.vector||`assets/logos/fallback/${key}.svg`}
function tripCarIconHtml(){return `<div class="trip-car-pin"><img src="assets/icons/trip-car-top.png" alt="" draggable="false"></div>`}
function setReplayMarkerRotation(angle=0){state.trip.currentHeading=angle;const el=state.replayMarker?.getElement?.();el?.style?.setProperty('--car-heading',`${angle}deg`)}
function ensureReplayMarker(lat,lon,angle=0){if(!(state.map&&window.L))return;const position=[lat,lon];if(!state.replayMarker){state.replayMarker=L.marker(position,{icon:L.divIcon({className:'trip-car-div-icon',html:tripCarIconHtml(),iconSize:[52,52],iconAnchor:[26,26]})}).addTo(state.map)}else state.replayMarker.setLatLng(position);setReplayMarkerRotation(angle)}
function routeHeading(a,b,offset=90){if(!a||!b)return state.trip.currentHeading||0;return Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI+offset}
function shortestAngle(from,to){return ((to-from+540)%360)-180}
function lerpHeading(from,to,t){return from+shortestAngle(from,to)*t}
function setFallbackCar(pos,angle=0){state.trip.currentHeading=angle;$('#fallbackCar').setAttribute('transform',`translate(${pos.x.toFixed(1)} ${pos.y.toFixed(1)}) rotate(${angle.toFixed(1)})`)}
function syncDemoButtons(){const primary=state.mockTimer?'توقف دمو':state.demoMode?'اجرای دوباره دمو':'شروع دمو';$('#mockToggle').textContent=primary;const start=$('#activateDemo');if(start)start.textContent=state.demoMode?'اجرای دوباره دمو':'شروع دمو'}
function activeVehicle(){return state.demoMode?state.demo?.vehicle:(state.data?.vehicles?.[state.vehicleIndex]||availableVehicles()[0])}
function activeLogo(v){return state.customLogo||(v?.isDemo?`assets/${v.logoAsset}`:logoPath(v))}
function availableVehicles(){const all=state.data.vehicles.map((v,index)=>({...v,index}));if(state.plan==='pro')return all;const allow=new Set(state.tiers.freeVehicleIndexes);return all.filter(v=>allow.has(v.index)&&v.segment==='passenger')}
function renderVehicles(){const list=availableVehicles(),makes=[...new Set(list.map(v=>v.make))];$('#makeSelect').innerHTML=makes.map(x=>`<option>${x}</option>`).join('');const current=state.data.vehicles[state.vehicleIndex];if(makes.includes(current?.make))$('#makeSelect').value=current.make;renderModels();const demoCard=state.demo?`<article class="vehicle-card demo-card ${state.demoMode?'selected':''}" data-demo="true"><img src="assets/${state.demo.vehicle.logoAsset}"><strong>${state.demo.vehicle.model}</strong><small>بدون اتصال واقعی</small></article>`:'';$('#vehicleGrid').innerHTML=demoCard+list.map(v=>`<article class="vehicle-card ${!state.demoMode&&v.index===state.vehicleIndex?'selected':''}" data-index="${v.index}"><img src="${logoPath(v)}" onerror="this.onerror=null;this.src='${logoFallback(v)}'"><strong>${v.model}</strong><small>${v.make}</small></article>`).join('');$$('.vehicle-card[data-index]').forEach(c=>c.onclick=()=>{$('#makeSelect').value=state.data.vehicles[c.dataset.index].make;renderModels();$('#modelSelect').value=c.dataset.index});$('.demo-card')?.addEventListener('click',activateDemo);syncDemoButtons()}
function renderModels(){const list=availableVehicles().filter(v=>v.make===$('#makeSelect').value);$('#modelSelect').innerHTML=list.map(v=>`<option value="${v.index}">${v.model}</option>`).join('');if(!state.demoMode&&list.some(v=>v.index===state.vehicleIndex))$('#modelSelect').value=state.vehicleIndex}
$('#makeSelect').onchange=renderModels;$('#activateVehicle').onclick=()=>{state.vehicleIndex=Number($('#modelSelect').value);state.demoMode=false;state.customLogo='';localStorage.removeItem('ecuCustomLogo');localStorage.setItem('ecuVehicle',state.vehicleIndex);localStorage.setItem('ecuDemoMode','false');stopDemo();renderActiveVehicle();renderVehicles();toast('پروفایل خودرو و لوگوی کارخانه فعال شد')};
function renderActiveVehicle(){const v=activeVehicle();if(!v)return;$('#vehicleName').textContent=`${v.make} ${v.model}`;$('#vehicleProtocol').textContent=(v.protocols||[]).join(' · ')||v.profile;const hero=$('#vehicleLogo');hero.onerror=()=>{hero.onerror=null;hero.src=logoFallback(v)};hero.src=activeLogo(v);$('#demoBadge').hidden=!state.demoMode;$('#dataModeLabel').textContent=state.demoMode?'داده آزمایشی':'داده خودرو';syncDemoButtons()}
$('#logoInput').onchange=e=>{const file=e.target.files[0];if(!file)return;if(file.size>1024*1024)return reportError(new AppFault('LOGO_TOO_LARGE','فایل لوگو بزرگ است','حداکثر اندازه لوگوی سفارشی یک مگابایت است.'));const r=new FileReader();r.onload=()=>{state.customLogo=r.result;localStorage.setItem('ecuCustomLogo',state.customLogo);renderActiveVehicle()};r.onerror=()=>reportError(r.error,{feature:'custom-logo'});r.readAsDataURL(file)};

function setNeedle(id,value,max,start=-140,end=140){const obj=$(id);try{const needle=obj.contentDocument?.getElementById('needle');if(needle){const svg=obj.contentDocument.documentElement,view=svg.viewBox.baseVal;const cx=view.width/2,cy=view.height*.68;needle.style.transformOrigin=`${cx}px ${cy}px`;needle.style.transform=`rotate(${start+(end-start)*Math.max(0,Math.min(1,value/max))}deg)`;needle.style.transition='transform .5s ease'}}catch(e){reportError(e,{feature:'gauge'},false)}}
function renderLive(){const l=state.live;$('#speedValue').textContent=`${fa(Math.round(l.speedKph||0))} km/h`;$('#rpmValue').textContent=`${fa(Math.round(l.rpm||0))} rpm`;$('#coolant').textContent=l.coolantC==null?'--':`${fa(l.coolantC)} °C`;$('#voltage').textContent=l.voltage==null?'--':`${fa(l.voltage.toFixed(1))} V`;$('#engineLoad').textContent=l.engineLoad==null?'--':`${fa(Math.round(l.engineLoad))}٪`;$('#fuelUse').textContent=l.speedKph>5?`${fa((5.5+l.engineLoad/20).toFixed(1))} L/100`:'--';setNeedle('#speedGauge',l.speedKph,220);setNeedle('#rpmGauge',l.rpm,7000);epsThemeRegistry.update(l)}
function demoSnapshot(tick){const phase=(tick%112)/112,drive=Math.sin(phase*Math.PI);const stop=(tick%42>30&&tick%42<37);const speed=stop?0:Math.max(0,8+104*Math.pow(Math.max(0,drive),1.25)+8*Math.sin(phase*Math.PI*7));const rpm=stop?780:820+speed*22+420*Math.abs(Math.sin(phase*Math.PI*9));return{rpm, speedKph:speed, coolantC:82+Math.round(12*Math.min(1,tick/80)), voltage:13.5+0.35*Math.sin(phase*Math.PI*4), engineLoad:18+Math.min(54,speed*.42+18*Math.abs(Math.sin(phase*Math.PI*5)))}}
function startDemo(){state.demoMode=true;localStorage.setItem('ecuDemoMode','true');if(state.mockTimer)clearInterval(state.mockTimer);state.demoTick=0;const step=()=>{state.live=demoSnapshot(state.demoTick++);renderLive()};step();state.mockTimer=setInterval(step,state.demo?.scenario?.sampleIntervalMs||800);renderActiveVehicle();renderVehicles();syncDemoButtons();seedDemoTrip()}
function stopDemo(){if(state.mockTimer){clearInterval(state.mockTimer);state.mockTimer=null}syncDemoButtons()}
function activateDemo(){state.customLogo='';localStorage.removeItem('ecuCustomLogo');startDemo();toast('پروفایل نمایشی فعال شد')}
$('#activateDemo').onclick=activateDemo;
$('#mockToggle').onclick=()=>state.mockTimer?stopDemo():startDemo();
$('#readDtcBtn').onclick=()=>{state.dtcs=(state.demoMode?state.demo.scenario.dtcs:[{code:'P0133',kind:'STORED',description:'پاسخ کند سنسور اکسیژن بانک ۱'},{code:'P0420',kind:'PENDING',description:'بازده کاتالیست پایین‌تر از آستانه'}]).map(x=>({...x}));renderDtcs()};
function renderDtcs(){$('#dtcList').innerHTML=state.dtcs.length?state.dtcs.map(x=>`<article class="dtc-item"><strong>${x.code}</strong><p>${x.description}<br>${x.kind}</p></article>`).join(''):'<p class="note">هنوز کدی خوانده نشده است.</p>'}
async function clearDtcs(){if(!state.dtcs.length)return toast('خطایی برای پاک‌کردن وجود ندارد');if(!confirm('موتور خاموش و سوییچ باز است؟ Mode 04 می‌تواند Freeze Frame و Readiness را پاک کند.'))return;if(state.demoMode){await new Promise(r=>setTimeout(r,450));state.dtcs=[];renderDtcs();return toast('خطاهای دمو پاک شدند؛ سهمیه واقعی مصرف نشد')}try{const a=await api('/api/v1/actions/dtc-clear/authorize',{method:'POST',body:'{}'}).then(r=>r.json());await new Promise(r=>setTimeout(r,500));state.dtcs=[];renderDtcs();await fetchTimeout(`${state.activeApi}/api/v1/actions/dtc-clear/complete`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${a.actionToken}`},body:JSON.stringify({success:true})});toast('خطاها پاک شدند');await refreshEntitlement()}catch(e){reportError(e,{feature:'clear-dtc'})}}
$('#clearDtcBtn').onclick=clearDtcs;
async function refreshEntitlement(){try{const x=await api('/api/v1/entitlements/me').then(r=>r.json());const left=x.clearDtcLimit<0?'نامحدود':Math.max(0,x.clearDtcLimit-x.clearDtcUsed);$('#clearQuota').textContent=x.pro?'نسخه پیشرفته: نامحدود':`نسخه رایگان: ${fa(left)} بار باقی مانده`;$('#clearQuotaSide').textContent=x.pro?'پاک‌کردن نامحدود':`${fa(left)} پاک‌کردن باقی مانده`}catch(e){$('#clearQuota').textContent='برای بررسی سهمیه، سرور را اجرا کن';reportError(e,{feature:'entitlement'},false)}}

function seedDemoTrip(){if(!state.demo?.demoTrip)return;const demo=state.demo.demoTrip,key=`ecuDemoTripSeeded:${demo.id}`;if(localStorage.getItem(key)==='1'&&trips().some(x=>x.id===demo.id))return;const now=Date.now()-(demo.points.at(-1)?.offsetSeconds||0)*1000,points=demo.points.map(p=>({lat:p.lat,lon:p.lon,t:now+p.offsetSeconds*1000,speed:p.speedKph,accuracy:6,rpm:p.rpm,label:p.label||null,stop:!!p.stop}));const all=trips().filter(x=>!x.demo);all.push({id:demo.id,titleFa:demo.titleFa,descriptionFa:demo.descriptionFa,startedAt:now,endedAt:now+(points.at(-1)?.t-now||0),points,demo:true,stops:demo.stops||[],checkpoints:demo.checkpoints||[]});saveTrips(all);localStorage.setItem(key,'1')}
function trips(){return JSON.parse(localStorage.getItem('ecuTrips')||'[]')}function saveTrips(x){localStorage.setItem('ecuTrips',JSON.stringify(x.slice(-100)));renderTripSelect()}
function hav(a,b){const r=6371e3,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lon-a.lon)*Math.PI/180;const q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*r*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function startTrip(){if(!navigator.geolocation)return reportError(new AppFault('GEO_UNAVAILABLE','موقعیت مکانی پشتیبانی نمی‌شود','مرورگر Geolocation API ندارد.'));state.trip.startedAt=Date.now();state.trip.points=[];$('#startTrip').disabled=true;$('#stopTrip').disabled=false;state.trip.watchId=navigator.geolocation.watchPosition(pos=>{const p={lat:pos.coords.latitude,lon:pos.coords.longitude,t:pos.timestamp,speed:Math.max(0,(pos.coords.speed||0)*3.6),accuracy:pos.coords.accuracy,rpm:state.live.rpm||0};if(p.accuracy>100)return;state.trip.points.push(p);updateTripStats(state.trip.points);drawRoute(state.trip.points,true)},e=>reportError(new AppFault(`GEO_${e.code}`,'خطای موقعیت مکانی',e.message,{permission:e.code===1}),{feature:'trip'}),{enableHighAccuracy:true,maximumAge:3000,timeout:15000})}
function stopTrip(){if(state.trip.watchId!=null)navigator.geolocation.clearWatch(state.trip.watchId);state.trip.watchId=null;$('#startTrip').disabled=false;$('#stopTrip').disabled=true;if(state.trip.points.length<2)return toast('نقطه کافی ثبت نشد');const all=trips();all.push({id:crypto.randomUUID(),startedAt:state.trip.startedAt,endedAt:Date.now(),points:state.trip.points});saveTrips(all);toast('سفر ذخیره شد')}
$('#startTrip').onclick=startTrip;$('#stopTrip').onclick=stopTrip;
function tripSummary(points){let distance=0,moving=0,stopped=0,max=0;for(let i=1;i<points.length;i++){const dt=Math.max(0,(points[i].t-points[i-1].t)/1000),d=hav(points[i-1],points[i]);if(d<1000)distance+=d;const speed=points[i].speed||d/dt*3.6||0;max=Math.max(max,speed);if(speed<2)stopped+=dt;else moving+=dt}return{distance,moving,stopped,max}}
function time(sec){const m=Math.floor(sec/60),s=Math.floor(sec%60);return `${fa(String(m).padStart(2,'0'))}:${fa(String(s).padStart(2,'0'))}`}
function updateTripStats(points){const x=tripSummary(points);$('#tripDistance').textContent=`${fa((x.distance/1000).toFixed(2))} km`;$('#tripMoving').textContent=time(x.moving);$('#tripStopped').textContent=time(x.stopped);$('#tripMaxSpeed').textContent=fa(Math.round(x.max))}
function renderTripSelect(){const all=trips();$('#tripSelect').innerHTML=all.length?all.map(x=>`<option value="${x.id}">${x.titleFa||new Date(x.startedAt).toLocaleString('fa-IR')} · ${fa((tripSummary(x.points).distance/1000).toFixed(1))} km</option>`).join(''):'<option>سفری ذخیره نشده</option>';if(all.length&&!$('#tripSelect').value)$('#tripSelect').value=all.at(-1).id}
const LEAFLET_CDNS=[
  {js:'https://unpkg.com/leaflet@1.9.4/dist/leaflet.js',css:'https://unpkg.com/leaflet@1.9.4/dist/leaflet.css'},
  {js:'https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.js',css:'https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.css'},
  {js:'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.js',css:'https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.css'}
];
function loadScript(src,timeout=4500){return new Promise((resolve,reject)=>{const s=document.createElement('script'),timer=setTimeout(()=>{s.remove();reject(new Error('timeout'))},timeout);s.src=src;s.async=true;s.onload=()=>{clearTimeout(timer);resolve()};s.onerror=()=>{clearTimeout(timer);s.remove();reject(new Error('load failed'))};document.head.appendChild(s)})}
function loadCss(href){if([...document.styleSheets].some(x=>x.href===href))return;const l=document.createElement('link');l.rel='stylesheet';l.href=href;document.head.appendChild(l)}
async function ensureLeaflet(){if(window.L)return true;for(const c of LEAFLET_CDNS){try{loadCss(c.css);await loadScript(c.js);if(window.L)return true}catch{}}return false}
async function initMap(){if(state.map)return true;if(state.mapLoading)return state.mapLoading;state.mapLoading=(async()=>{const status=$('#mapStatus');status.textContent='نقشه آفلاین آماده؛ تلاش برای نقشه آنلاین…';const ok=await ensureLeaflet();if(!ok){status.textContent='نقشه آنلاین در دسترس نیست؛ مسیر روی نقشه آفلاین نمایش داده می‌شود';$('#mapProvider').textContent='Offline SVG';return false}try{state.map=L.map('leafletMap',{zoomControl:true,preferCanvas:true}).setView([35.6892,51.389],12);let tileErrors=0;const tiles=L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap',crossOrigin:true});tiles.on('tileerror',()=>{tileErrors++;if(tileErrors===4){status.textContent='کاشی‌های آنلاین مسدودند؛ مسیر آفلاین همچنان فعال است';$('#leafletMap').classList.remove('ready');$('#mapProvider').textContent='Offline SVG'}});tiles.on('load',()=>{$('#leafletMap').classList.add('ready');status.textContent='نقشه آنلاین و مسیر آفلاین آماده‌اند';$('#mapProvider').textContent='OpenStreetMap + Offline'});tiles.addTo(state.map);setTimeout(()=>{state.map?.invalidateSize?.(true);if(tileErrors===0)$('#leafletMap').classList.add('ready')},250);return true}catch(e){reportError(e,{feature:'map-init'},false);status.textContent='خطا در نقشه آنلاین؛ مسیر آفلاین فعال است';return false}})().finally(()=>state.mapLoading=null);return state.mapLoading}
function projectOffline(points){const minLat=Math.min(...points.map(p=>p.lat)),maxLat=Math.max(...points.map(p=>p.lat)),minLon=Math.min(...points.map(p=>p.lon)),maxLon=Math.max(...points.map(p=>p.lon));const pad=58,w=884,h=504;return points.map(p=>({x:pad+(p.lon-minLon)/(maxLon-minLon||1)*w,y:560-(p.lat-minLat)/(maxLat-minLat||1)*h}))}
function renderOfflineRoute(points,trip=null,trailIndex=points.length-1,markerPoint=null,angle=null){if(!points.length)return;const routeChanged=state.trip.projectionSource!==points||state.trip.projection?.length!==points.length,xy=routeChanged?projectOffline(points):state.trip.projection;if(routeChanged){state.trip.projection=xy;state.trip.projectionSource=points;$('#fallbackRoute').setAttribute('points',xy.map(p=>`${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(' '));const g=$('#fallbackStops');g.innerHTML='';(trip?.stops||[]).forEach(s=>{let nearest=0,best=Infinity;points.forEach((p,i)=>{const d=Math.abs(p.lat-s.lat)+Math.abs(p.lon-s.lon);if(d<best){best=d;nearest=i}});const q=xy[nearest],c=document.createElementNS('http://www.w3.org/2000/svg','circle');c.setAttribute('class','fallback-stop');c.setAttribute('cx',q.x);c.setAttribute('cy',q.y);c.setAttribute('r','8');g.appendChild(c);const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('class','fallback-stop-label');t.setAttribute('x',q.x+12);t.setAttribute('y',q.y-10);t.textContent=s.nameFa||'توقف';g.appendChild(t)})}const limit=Math.max(1,Math.min(xy.length,trailIndex+1)),trail=xy.slice(0,limit);if(markerPoint)trail.push(markerPoint);$('#fallbackTrail').setAttribute('points',trail.map(p=>`${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(' '));const car=markerPoint||xy[Math.max(0,Math.min(trailIndex,xy.length-1))],heading=angle??routeHeading(xy[Math.max(0,trailIndex-1)],xy[Math.min(xy.length-1,trailIndex+1)]);setFallbackCar(car,heading)}
function fitTripMap(points=null,animate=true){const route=points||state.trip.currentTrip?.points||selectedTrip()?.points||state.trip.points;if(!route?.length)return false;if(state.map&&window.L){const bounds=L.latLngBounds(route.map(p=>[p.lat,p.lon]));if(bounds.isValid()){state.map.invalidateSize(false);state.map.fitBounds(bounds,{paddingTopLeft:[42,58],paddingBottomRight:[42,72],maxZoom:13,animate,duration:animate ? .45 : 0});$('#mapStatus').textContent='کل مسیر روی نقشه فیت شده است';return true}}return false}
function drawRoute(points,fit=false,trip=null,trailIndex=points.length-1){if(!points.length)return;renderOfflineRoute(points,trip,trailIndex);if(state.map&&window.L){const latlngs=points.map(p=>[p.lat,p.lon]);if(state.routeLine)state.routeLine.setLatLngs(latlngs);else state.routeLine=L.polyline(latlngs,{color:'#55dff6',weight:5}).addTo(state.map);const target=latlngs[Math.max(0,Math.min(trailIndex,latlngs.length-1))];ensureReplayMarker(target[0],target[1],state.trip.currentHeading||0);if(fit)fitTripMap(points,false);state.map.invalidateSize(false)}}
function selectedTrip(){return trips().find(x=>x.id===$('#tripSelect').value)}
function previewSelectedTrip(){const trip=selectedTrip();if(!trip)return;stopReplay(false);state.trip.currentTrip=trip;updateTripStats(trip.points);$('#timeline').max=Math.max(0,trip.points.length-1);$('#timeline').value=0;drawRoute(trip.points,true,trip,0);renderStops(trip);updateReplayPoint(0,false)}
function renderStops(trip){$('#stopList').innerHTML=(trip.stops||[]).length?(trip.stops||[]).map(s=>`<article><strong>${s.nameFa||'توقف'}</strong><small>${fa(Math.max(1,Math.round((s.durationSeconds||0)/60)))} دقیقه</small></article>`).join(''):'<p class="note">توقف ثبت‌شده‌ای وجود ندارد.</p>';if(state.map&&window.L){state.stopMarkers.forEach(m=>m.remove());state.stopMarkers=[];(trip.stops||[]).forEach(s=>state.stopMarkers.push(L.marker([s.lat,s.lon]).addTo(state.map).bindPopup(`<b>${s.nameFa||'توقف'}</b><br>${fa(Math.round((s.durationSeconds||0)/60))} دقیقه توقف`)))}}
$('#tripSelect').onchange=previewSelectedTrip;
$('#loadDemoTrip').onclick=()=>{seedDemoTrip();renderTripSelect();const d=trips().find(x=>x.demo);if(d){$('#tripSelect').value=d.id;previewSelectedTrip();toast('سفر نمایشی تهران بارگذاری شد')}};
$$('.speed-buttons button').forEach(b=>b.onclick=()=>{const v=Number(b.dataset.speed);if(state.plan!=='pro'&&v>2)return go('store');state.trip.replaySpeed=v;$$('.speed-buttons button').forEach(x=>x.classList.toggle('active',x===b));if(state.trip.replayTimer||state.trip.replayFrame){stopReplay(false);state.trip.paused=false;replay(false)}});
function stopReplay(resetButton=true){if(state.trip.replayTimer){clearTimeout(state.trip.replayTimer);state.trip.replayTimer=null}if(state.trip.replayFrame){cancelAnimationFrame(state.trip.replayFrame);state.trip.replayFrame=null}if(resetButton)$('#replayTrip').textContent='پخش'}
function updateReplayPoint(index,follow=true){const trip=state.trip.currentTrip||selectedTrip();if(!trip?.points?.length)return;const i=Math.max(0,Math.min(index,trip.points.length-1)),p=trip.points[i];state.trip.replayIndex=i;$('#timeline').value=i;const elapsed=Math.max(0,((p.t||0)-(trip.points[0].t||0))/1000);$('#replayInfo').textContent=`${p.label?`${p.label} · `:''}سرعت ${fa(Math.round(p.speed||p.speedKph||0))} km/h · RPM ${fa(Math.round(p.rpm||0))}${p.stop?' · توقف':''} · زمان ${time(elapsed)}`;const xy=state.trip.projection||projectOffline(trip.points);const current=xy[i],next=xy[Math.min(xy.length-1,i+1)]||current;const angle=routeHeading(current,next);renderOfflineRoute(trip.points,trip,i,null,angle);if(state.map&&window.L){ensureReplayMarker(p.lat,p.lon,angle);if(follow)fitTripMap(trip.points,false)}}
function animateReplaySegment(i){const trip=state.trip.currentTrip||selectedTrip();if(!trip?.points?.length)return;if(i>=trip.points.length-1){updateReplayPoint(trip.points.length-1,false);stopReplay();toast('بازپخش تمام شد');return}const points=trip.points,xy=state.trip.projection||projectOffline(points),from=points[i],to=points[i+1],fromXY=xy[i],toXY=xy[i+1],targetAngle=routeHeading(fromXY,toXY),startAngle=state.trip.currentHeading||targetAngle,started=performance.now(),recordedDelta=Math.max(0,(to.t||0)-(from.t||0)),duration=Math.max(240,Math.min(1600,(recordedDelta||850)/state.trip.replaySpeed));const step=now=>{if(state.trip.paused)return;const t=Math.min(1,(now-started)/duration),marker={x:fromXY.x+(toXY.x-fromXY.x)*t,y:fromXY.y+(toXY.y-fromXY.y)*t},lat=from.lat+(to.lat-from.lat)*t,lon=from.lon+(to.lon-from.lon)*t,speed=(from.speed||0)+((to.speed||0)-(from.speed||0))*t,rpm=(from.rpm||0)+((to.rpm||0)-(from.rpm||0))*t,elapsed=Math.max(0,(((from.t||0)+((to.t||from.t||0)-(from.t||0))*t)-(points[0].t||0))/1000),angle=lerpHeading(startAngle,targetAngle,Math.min(1,t*2.2));state.trip.replayIndex=i;$('#timeline').value=(i+t).toFixed(3);$('#replayInfo').textContent=`${(t<.5?from.label:to.label)?`${t<.5?from.label:to.label} · `:''}سرعت ${fa(Math.round(speed))} km/h · RPM ${fa(Math.round(rpm))}${t>.6&&to.stop?' · توقف':''} · زمان ${time(elapsed)}`;renderOfflineRoute(points,trip,i,marker,angle);if(state.map&&window.L)ensureReplayMarker(lat,lon,angle);if(t<1)state.trip.replayFrame=requestAnimationFrame(step);else{state.trip.replayIndex=i+1;animateReplaySegment(i+1)}};state.trip.replayFrame=requestAnimationFrame(step)}
function replay(fromStart=false){const trip=selectedTrip();if(!trip)return toast('سفری انتخاب نشده');state.trip.currentTrip=trip;if(fromStart||state.trip.replayIndex>=trip.points.length-1)state.trip.replayIndex=0;state.trip.paused=false;stopReplay(false);fitTripMap(trip.points,true);$('#replayTrip').textContent='در حال پخش';animateReplaySegment(Math.floor(state.trip.replayIndex))}
$('#fitTripMap').onclick=()=>{const trip=state.trip.currentTrip||selectedTrip();if(trip?.points?.length)fitTripMap(trip.points,true);else if(state.trip.points.length)fitTripMap(state.trip.points,true);else toast('هنوز مسیری برای نمایش وجود ندارد')};$('#replayTrip').onclick=()=>replay(false);$('#pauseTrip').onclick=()=>{state.trip.paused=true;stopReplay();$('#replayInfo').textContent+=' · مکث'};$('#restartTrip').onclick=()=>replay(true);$('#timeline').oninput=e=>{stopReplay();state.trip.paused=true;updateReplayPoint(Math.round(Number(e.target.value)),false)};$('#exportTrip').onclick=()=>{const t=selectedTrip();if(!t)return toast('سفری انتخاب نشده');const a=document.createElement('a'),blob=new Blob([JSON.stringify(t,null,2)],{type:'application/json'});a.href=URL.createObjectURL(blob);a.download=`ecu-pulse-trip-${t.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000)};$('#deleteTrip').onclick=()=>{const t=selectedTrip();if(!t||t.demo)return toast('سفر نمایشی حذف نمی‌شود');if(!confirm('این سفر حذف شود؟'))return;saveTrips(trips().filter(x=>x.id!==t.id));previewSelectedTrip()};

function localAnalyze(){const alerts=[];let score=94;for(const d of state.dtcs){score-=d.kind==='PERMANENT'?14:d.kind==='STORED'?10:6;alerts.push({severity:d.kind==='PERMANENT'?'high':'medium',title:`کد ${d.code}`,detail:d.description||'کد خطای ECU نیازمند بررسی مرحله‌ای است.'})}if((state.live.coolantC||0)>105){score-=18;alerts.push({severity:'high',title:'دمای موتور بالا',detail:'دمای آب بالاتر از محدوده عادی مشاهده شد.'})}if(state.live.voltage!=null&&state.live.voltage<12){score-=10;alerts.push({severity:'medium',title:'ولتاژ پایین',detail:'باتری، دینام و اتصالات بررسی شوند.'})}return{reportId:`local-${crypto.randomUUID()}`,generatedAt:new Date().toISOString(),score:Math.max(0,score),summary:alerts.length?'در داده‌های فعلی مواردی برای بررسی پیدا شد.':'در داده‌های فعلی هشدار مهمی مشاهده نشد.',alerts,recommendations:['کدها را همراه Freeze Frame و داده زنده بررسی کنید.','پاک‌کردن کد به‌تنهایی تعمیر محسوب نمی‌شود.'],source:'local-development-analysis-v0.9.0'}}
function renderAnalysis(report){state.lastReport=report;$('#analysisResult').className='report';$('#analysisResult').innerHTML=`<strong class="report-score">${fa(report.score)}</strong><h2>${report.summary}</h2>${(report.alerts||[]).map(a=>`<article><strong>${a.title}</strong><p>${a.detail}</p></article>`).join('')||'<p>هشدار فعالی ثبت نشده است.</p>'}`;$('#analysisSource').textContent=report.source?.startsWith('local')?'تحلیل محلی آزمایشی؛ سرور Node در دسترس نبود.':'تحلیل توسط سرور Diageman دریافت شد.';$('#pdfBtn').disabled=false}
async function analyze(){if(state.plan!=='pro')return go('store');$('#analysisResult').className='report-empty';$('#analysisResult').textContent='در حال تحلیل…';try{const v=activeVehicle();const report=await api('/api/v1/analyze',{method:'POST',body:JSON.stringify({vehicle:v,live:state.live,dtcs:state.dtcs,trip:trips().at(-1)||null})}).then(r=>r.json());renderAnalysis(report)}catch(e){const report=localAnalyze();renderAnalysis(report);reportError(e,{feature:'analysis-server-fallback'},false);toast('سرور در دسترس نبود؛ تحلیل محلی آزمایشی نمایش داده شد')}}
function printLocalReport(report){const w=window.open('','_blank');if(!w)throw new AppFault('POPUP_BLOCKED','پنجره گزارش مسدود شد','اجازه بازشدن پنجره جدید را در مرورگر فعال کنید.');w.document.write(`<!doctype html><html lang="fa" dir="rtl"><meta charset="utf-8"><title>گزارش ECU Pulse</title><style>body{font-family:Tahoma,sans-serif;max-width:850px;margin:40px auto;line-height:1.9;color:#172235}h1{color:#087b96}.score{font-size:52px;font-weight:bold}.item{border:1px solid #ccd5df;border-radius:12px;padding:12px;margin:10px 0}@media print{button{display:none}}</style><h1>گزارش تحلیل ECU Pulse</h1><div class="score">${report.score}/100</div><h2>${report.summary}</h2>${(report.alerts||[]).map(a=>`<div class="item"><b>${a.title}</b><p>${a.detail}</p></div>`).join('')}<p>شناسه: ${report.reportId}</p><button onclick="print()">چاپ / ذخیره PDF</button></html>`);w.document.close()}
$('#analyzeBtn').onclick=analyze;$('#pdfBtn').onclick=async()=>{if(!state.lastReport)return;try{if(state.lastReport.source?.startsWith('local'))return printLocalReport(state.lastReport);const r=await api('/api/v1/reports/pdf',{method:'POST',body:JSON.stringify(state.lastReport)});const blob=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ecu-pulse-${state.lastReport.reportId}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000)}catch(e){reportError(e,{feature:'pdf-server'},false);printLocalReport(state.lastReport)}};
async function loadOffers(){try{state.offers=await api('/api/v1/offers').then(r=>r.json()).then(x=>x.offers);$('#offers').innerHTML=state.offers.map(o=>`<article class="offer-card"><strong>${o.titleFa}</strong><span class="price">${fa(o.basePrice.toLocaleString())} ${o.currency}</span><button disabled>خرید از اپ Android</button></article>`).join('');$('#couponOffer').innerHTML=state.offers.map(o=>`<option value="${o.id}">${o.titleFa}</option>`).join('')}catch(e){reportError(e,{feature:'offers'},false);$('#offers').innerHTML='<p class="note">سرور فروش در دسترس نیست.</p>'}}
$('#applyCoupon').onclick=async()=>{try{const q=await api('/api/v1/coupons/quote',{method:'POST',body:JSON.stringify({code:$('#couponCode').value,offerId:$('#couponOffer').value,store:'googlePlay'})}).then(r=>r.json());$('#quoteResult').innerHTML=`تخفیف ${fa(q.percent)}٪ · مبلغ نهایی سرور: <strong>${fa(q.finalPrice.toLocaleString())} ${q.currency}</strong> · اعتبار تا ${new Date(q.expiresAt).toLocaleTimeString('fa-IR')}`}catch(e){reportError(e,{feature:'coupon'})}};

function renderErrors(){$('#errorList').innerHTML=state.errors.length?[...state.errors].reverse().map(e=>`<article class="error-card"><strong>${e.code} — ${e.title}</strong><small> · ${new Date(e.at).toLocaleString('fa-IR')} · ${e.sent?'ارسال شد':'محلی'}</small><p>${e.detail}</p><button data-error="${e.id}">ارسال به سرور</button></article>`).join(''):'<p class="note">خطایی ثبت نشده است.</p>';$$('[data-error]').forEach(b=>b.onclick=()=>sendError(b.dataset.error))}
async function sendError(id){const item=state.errors.find(x=>x.id===id);if(!item)return;try{await api('/api/v1/errors/report',{method:'POST',body:JSON.stringify(item)});item.sent=true;persistErrors();renderErrors();closeErrorDialog();toast('گزارش برای سرور ارسال شد')}catch(e){toast(`ارسال ناموفق: ${e.message}`)}}
$('#sendAllErrors').onclick=async()=>{for(const e of state.errors.filter(x=>!x.sent))await sendError(e.id)};
$('#saveSettings').onclick=()=>{localStorage.setItem('ecuRemoteApi',$('#remoteApi').value.trim());localStorage.setItem('ecuLocalApi',$('#localApi').value.trim());applyTheme($('#themeSelect').value);state.token=null;applyPlan();toast('تنظیمات ذخیره شد')};
function setDevelopmentPlan(pro){state.plan=pro?'pro':'free';localStorage.setItem('ecuDevProUnlocked',String(pro));localStorage.setItem('ecuPlan',state.plan);state.token=null;applyPlan();toast(pro?'نسخه پیشرفته آزمایشی فعال شد':'نسخه رایگان فعال شد')}
function tryUnlockPro(raw){const code=String(raw||'').trim();if(code!==DEV_PRO_CODE){toast('کد فعال‌سازی نادرست است');return false}setDevelopmentPlan(true);return true}
$('#unlockProBtn').onclick=()=>{if(tryUnlockPro($('#devProCode').value))$('#devProCode').value=''};
$('#storeUnlockProBtn').onclick=()=>{if(tryUnlockPro($('#storeDevProCode').value)){ $('#storeDevProCode').value='';go('procenter')}};
$('#disableProBtn').onclick=()=>setDevelopmentPlan(false);
function activateAdvancedCard(card){if(state.plan!=='pro')return toast('ابتدا نسخه پیشرفته را با کد ۱۲۳۴ فعال کن');if(card.dataset.open)return go(card.dataset.open);if(card.dataset.action==='dtc-clear'){go('dashboard');setTimeout(()=>$('#clearDtcBtn')?.scrollIntoView({behavior:'smooth',block:'center'}),100)}if(card.dataset.action==='pdf'){go('analysis');setTimeout(()=>state.lastReport?$('#pdfBtn').click():analyze(),100)}}
$$('.pro-feature').forEach(card=>{card.addEventListener('click',e=>{if(e.target.closest('button')||e.currentTarget===card)activateAdvancedCard(card)});card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activateAdvancedCard(card)}})});
function applyPlan(){const pro=state.plan==='pro';$('#sidePlan').textContent=pro?'PRO DEV':'FREE';$('#catalogBadge').textContent=pro?'کاتالوگ کامل':'فهرست رایگان ۱۰٪';$$('.pro-only').forEach(x=>x.classList.toggle('locked',!pro));$$('.pro-feature').forEach(x=>x.classList.toggle('locked',!pro));$('.advanced-nav')?.classList.toggle('unlocked',pro);if($('#proNavBadge'))$('#proNavBadge').textContent=pro?'فعال':'قفل';if($('#proCenterBadge'))$('#proCenterBadge').textContent=pro?'PRO فعال':'قفل';if($('#proUnlockStatus'))$('#proUnlockStatus').textContent=pro?'نسخه پیشرفته آزمایشی فعال است':'نسخه رایگان فعال است';$('.dev-unlock')?.classList.toggle('unlocked',pro);if($('#unlockProBtn'))$('#unlockProBtn').hidden=pro;if($('#disableProBtn'))$('#disableProBtn').hidden=!pro;if($('#planStatusInput'))$('#planStatusInput').value=pro?'پیشرفته آزمایشی':'رایگان';renderVehicles();renderActiveVehicle();refreshEntitlement()}


function syncMyDiagHome(){
  const v=activeVehicle();
  if(!v)return;
  $('#mydiagVehicleName').textContent=`${v.make} ${v.model}`;
  const logo=$('#mydiagVehicleLogo');logo.onerror=()=>{logo.onerror=null;logo.src=logoFallback(v)};logo.src=activeLogo(v);
  $('#mydiagSpeed').textContent=`${fa(Math.round(state.live.speedKph||0))} km/h`;
  $('#mydiagRpm').textContent=`${fa(Math.round(state.live.rpm||0))} rpm`;
  $('#mydiagDtcCount').textContent=fa(state.dtcs.length);
  $('#mydiagConnectionState').textContent=state.demoMode?'اتصال شبیه‌ساز فعال است':'منتظر اتصال ELM327';
}
function selectedTripForStyle(){return selectedTrip?.()||trips?.().at(-1)||null}
function calculateDrivingStyle(){
  const trip=selectedTripForStyle();
  if(!trip?.points?.length)return toast('سفری برای تحلیل انتخاب نشده است');
  const speeds=trip.points.map(p=>Number(p.speedKph||p.speed||0));
  let accel=0,brake=0;
  for(let i=1;i<speeds.length;i++){const d=speeds[i]-speeds[i-1];if(d>12)accel++;if(d<-14)brake++}
  const idle=(trip.stops||[]).length;
  const max=Math.max(0,...speeds);
  const score=Math.max(35,100-accel*4-brake*5-idle*2-Math.max(0,max-100)*.4);
  $('#styleScore').textContent=fa(Math.round(score));
  $('#rapidAccelCount').textContent=fa(accel);
  $('#rapidBrakeCount').textContent=fa(brake);
  $('#idleEventCount').textContent=fa(idle);
  $('#styleMaxSpeed').textContent=fa(Math.round(max));
  toast('امتیاز رانندگی از مسیر محاسبه شد');
}
$('#recalculateStyle').onclick=calculateDrivingStyle;
function renderParking(){
  const saved=JSON.parse(localStorage.getItem('ecuParking')||'null');
  $('#parkingStatus').textContent=saved?`عرض ${saved.lat.toFixed(6)} · طول ${saved.lon.toFixed(6)} · ${new Date(saved.at).toLocaleString('fa-IR')}`:'هنوز موقعیتی ذخیره نشده است.';
}
$('#saveParking').onclick=()=>{
  if(!navigator.geolocation)return reportError(new AppFault('GEO_UNSUPPORTED','موقعیت مکانی پشتیبانی نمی‌شود','مرورگر این دستگاه Geolocation ندارد.'));
  navigator.geolocation.getCurrentPosition(pos=>{localStorage.setItem('ecuParking',JSON.stringify({lat:pos.coords.latitude,lon:pos.coords.longitude,accuracy:pos.coords.accuracy,at:new Date().toISOString()}));renderParking();toast('محل پارک ذخیره شد')},e=>reportError(new AppFault(`GEO_${e.code}`,'ذخیره محل پارک ناموفق بود',e.message),{feature:'parking'}),{enableHighAccuracy:true,timeout:12000});
};
$('#clearParking').onclick=()=>{localStorage.removeItem('ecuParking');renderParking();toast('محل پارک حذف شد')};
$('#dashcamInput').onchange=e=>{const file=e.target.files?.[0];if(!file)return;const video=$('#dashcamVideo');if(video.dataset.url)URL.revokeObjectURL(video.dataset.url);const url=URL.createObjectURL(file);video.dataset.url=url;video.src=url;video.play().catch(()=>{})};
renderParking();

async function init(){try{[state.data,state.tiers,state.logos,state.demo]=await Promise.all([loadJson('data/core-data.json'),loadJson('data/product-tiers.json'),loadJson('data/brand-logos.json?v=1.4'),loadJson('data/demo-profile.json')]);applyTheme(state.theme);$('#remoteApi').value=localStorage.getItem('ecuRemoteApi')||'https://diageman.ir';$('#localApi').value=localStorage.getItem('ecuLocalApi')||'http://127.0.0.1:4030';$('#apiBase').value=$('#localApi').value;seedDemoTrip();renderActiveVehicle();syncMyDiagHome();renderVehicles();renderDtcs();renderTripSelect();renderErrors();applyPlan();if(state.demoMode)startDemo();setInterval(syncMyDiagHome,750);setTimeout(()=>initMap(),350)}catch(e){reportError(e,{feature:'startup'})}}
init();
